# Build script for RuneLauncher using CMake and Single EXE embedding generator
# Usage: .\build.ps1

# 1. Build React UI
Write-Host "Building React UI..."
Push-Location ui
npm run build
if ($LASTEXITCODE -ne 0) {
    Write-Host "React UI Build Failed" -ForegroundColor Red
    Pop-Location
    exit $LASTEXITCODE
}
Pop-Location

# 2. Ensure CMake is configured so WebView2 SDK is downloaded and unpacked
if (-not (Test-Path "build_cmake")) {
    New-Item -ItemType Directory -Path "build_cmake" | Out-Null
}

if (-not (Test-Path "build_cmake/webview2_sdk/build/native/x64/WebView2Loader.dll")) {
    Write-Host "Configuring CMake first to resolve dependencies..."
    cmake -B build_cmake -G "Visual Studio 18 2026" -A x64
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Initial CMake Config Failed" -ForegroundColor Red
        exit $LASTEXITCODE
    }
}

# 3. Generate src/ui/GeneratedResources.cpp from static assets
Write-Host "Generating Embedded Resources..."
$cppPath = "src/ui/GeneratedResources.cpp"
$utf8 = New-Object System.Text.UTF8Encoding($false) # No BOM
$stream = New-Object System.IO.FileStream($cppPath, [System.IO.FileMode]::Create, [System.IO.FileAccess]::Write)
$writer = New-Object System.IO.StreamWriter($stream, $utf8)

$writer.WriteLine("// Auto-generated by build.ps1. Do not modify.")
$writer.WriteLine("#include ""ui/GeneratedResources.hpp""")
$writer.WriteLine()
$writer.WriteLine("namespace rune {")
$writer.WriteLine()

# Function to write hex bytes to stream efficiently
function Write-HexPayload([string]$filePath, [string]$varName) {
    $bytes = [System.IO.File]::ReadAllBytes($filePath)
    $writer.WriteLine("const unsigned char ${varName}[] = {")
    $hex = [System.BitConverter]::ToString($bytes).Replace("-", ",0x")
    if ($hex.Length -gt 0) {
        $writer.Write("0x" + $hex)
    }
    $writer.WriteLine()
    $writer.WriteLine("};")
    $writer.WriteLine("const size_t ${varName}_SIZE = $($bytes.Length);")
    $writer.WriteLine()
}

# Embed WebView2Loader.dll
Write-HexPayload "build_cmake/webview2_sdk/build/native/x64/WebView2Loader.dll" "EMBEDDED_LOADER_DLL"

# Embed RuneCore.dll
Write-HexPayload "RuneCore.dll" "EMBEDDED_RUNE_CORE_DLL"

# Embed UI files individually
$uiFiles = Get-ChildItem -Path "ui/dist" -Recurse -File
$fileList = New-Object System.Collections.Generic.List[PSObject]
$fileIndex = 0

foreach ($file in $uiFiles) {
    $relativePath = $file.FullName.Substring((Get-Item "ui/dist").FullName.Length + 1).Replace("\", "/")
    $varName = "UI_FILE_$fileIndex"
    
    # Write raw hex payload
    Write-HexPayload $file.FullName $varName
    
    # Track metadata
    $fileList.Add([PSCustomObject]@{
            RelativePath = $relativePath
            VarName      = $varName
        })
    $fileIndex++
}

# Write index array
$writer.WriteLine("const EmbeddedFile EMBEDDED_UI_FILES[] = {")
foreach ($item in $fileList) {
    $writer.WriteLine("    {""$($item.RelativePath)"", $($item.VarName), $($item.VarName)_SIZE},")
}
$writer.WriteLine("};")
$writer.WriteLine("const size_t EMBEDDED_UI_FILES_COUNT = $($fileList.Count);")
$writer.WriteLine()
$writer.WriteLine("} // namespace rune")

$writer.Close()
$stream.Close()

# 4. Standard Build
Write-Host "Configuring and building project with CMake..."
cmake -B build_cmake -G "Visual Studio 18 2026" -A x64
if ($LASTEXITCODE -ne 0) {
    Write-Host "CMake Configuration Failed" -ForegroundColor Red
    exit $LASTEXITCODE
}

cmake --build build_cmake --config Release
if ($LASTEXITCODE -eq 0) {
    Write-Host "Build Succeeded: build_cmake/Release/launcher.exe" -ForegroundColor Green
}
else {
    Write-Host "Build Failed" -ForegroundColor Red
    exit $LASTEXITCODE
}
